.TH BASE64E

.SH NAME
base64e - encode a string in Base64 format

.SH SYNOPSIS
base64e [string]

.SH DESCRIPTION
The base64e function encodes a string in Base64 format.

The function takes a string as its argument and outputs the Base64-encoded form of the string to stdout. The function uses the 'base64' utility to perform the encoding.

.SH EXAMPLES
To use the base64e function to encode a string like "hello":

base64e hello

The function will output the Base64-encoded form of "hello", which is "aGVsbG8=".

.SH SEE ALSO
base64(1), sh(1)

.SH COLOPHON
This page is part of release 4.16 of the Linux man-pages project.

.SH AUTHOR
Ramo Mislimi (mislimi.ramo@gmail.com)
