services:
  samba:
    image: dperson/samba:latest
    container_name: samba
    restart: unless-stopped
    networks: [proxy]
    ports:
      - "445:445/tcp"
    environment:
      - TZ=Europe/Stockholm

      - USERID=1000
      - GROUPID=1000

      - USER=${USER}
    volumes:
      - /opt/docker/samba/config/smb.conf:/etc/samba/smb.conf:ro
      - /opt/docker/audiobookshelf/audiobooks:/audiobooks
      - /opt/docker/audiobookshelf/podcasts:/podcasts
      - /home/ramo/retroarch:/retroarch

networks:
  proxy:
    external: true
