services:
  authentik:
    image: ghcr.io/goauthentik/server:2026.2.1
    container_name: authentik
    restart: unless-stopped
    networks: [proxy]
    command: server
    depends_on:
      authentik-postgres:
        condition: service_healthy
    environment:
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgres
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: ${POSTGRES_PASSWORD}
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
    volumes:
      - /opt/docker/authentik/server/data:/data
      - /opt/docker/authentik/server/templates:/templates
      - /opt/docker/authentik/media:/media:ro

  authentik-worker:
    image: ghcr.io/goauthentik/server:2026.2.1
    container_name: authentik-worker
    restart: unless-stopped
    networks: [proxy]
    command: worker
    depends_on:
      authentik-postgres:
        condition: service_healthy
    environment:
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgres
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: ${POSTGRES_PASSWORD}
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker/authentik/server/data:/data
      - /opt/docker/authentik/server/certs:/certs
      - /opt/docker/authentik/server/templates:/templates

  authentik-postgres:
    image: postgres:16-alpine
    container_name: authentik-postgres
    restart: unless-stopped
    networks: [proxy]
    environment:
      POSTGRES_DB: authentik
      POSTGRES_USER: authentik
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
        - CMD-SHELL
        - pg_isready -d authentik -U authentik
      timeout: 5s
    volumes:
      - /opt/docker/authentik/postgres/data:/var/lib/postgresql/data

networks:
  proxy:
    external: true
