services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.0.2
    container_name: uptime-kuma
    restart: unless-stopped
    networks: [proxy]
    volumes:
      - /opt/docker/uptime-kuma/data:/app/data
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
    environment:
      - TZ=Europe/Stockholm
      - UMASK=0022
      - NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt

networks:
  proxy:
    external: true
