.TH JSON-DIFF 1
.SH NAME
json-diff - compare two JSON files using jq to sort keys and then diff.

.SH SYNOPSIS
.B json-diff
.IR FILE1 FILE2 [DIFF-OPTIONS...]

.SH DESCRIPTION
The
.B json-diff
function is used to compare two JSON files after sorting their keys with jq. This is particularly useful to see if two JSON files are functionally equivalent regardless of the order of their keys.

The function takes two mandatory arguments which are paths to the JSON files to be compared, followed by optional arguments to pass to the
.B diff
command. It uses
.B jq
to sort the keys in both files and pipes the sorted JSON to
.B diff.
If there are differences between the two sorted JSON files, they will be output by the
.B diff
command.

.SH USAGE
To compare two JSON files,
.I file1.json
and
.I file2.json
:

.B json-diff file1.json file2.json

If the two JSON files are equivalent (after sorting keys), there will be no output. If there are differences, they will be displayed line by line in the diff format.

To pass options to the
.B diff
command, simply include them after the file names:

.B json-diff file1.json file2.json --brief

This would use the `--brief` option of the
.B diff
command to show only when files differ.

.SH SEE ALSO
jq(1), diff(1), sh(1)

.SH AUTHOR
Ramo Mislimi (mislimi.ramo@gmail.com)
