services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped
    networks: [proxy]
    volumes:
      - /opt/docker/audiobookshelf/audiobooks:/audiobooks
      - /opt/docker/audiobookshelf/metadata:/metadata
      - /opt/docker/audiobookshelf/config:/config
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
    environment:
      - NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt

networks:
  proxy:
    external: true
