services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest-fat
    container_name: stirling-pdf
    restart: unless-stopped
    networks: [proxy]
    volumes:
      - /opt/docker/stirling-pdf/configs:/configs
    environment:
      - MODE=BOTH
      - LANGS=en_GB,sv_SE
      - BACKEND_INTERNAL_PORT=8081

      - SECURITY_LOGINMETHOD=normal
      - SECURITY_ENABLELOGIN=true

      # - SECURITY_OAUTH2_ENABLED=true
      # - SECURITY_OAUTH2_ISSUER=https://authentik.arpa/application/o/stirling-pdf/
      # - SECURITY_OAUTH2_CLIENTID=kVFS5Zz0696cSU34pudav4D3LJDf1mx3rXl9P0cy
      # - SECURITY_OAUTH2_CLIENTSECRET=${SECURITY_OAUTH2_CLIENTSECRET}
      # - SECURITY_OAUTH2_SCOPES=openid, profile, email
      # - SECURITY_OAUTH2_USEASUSERNAME=preferred_username
      # - SECURITY_OAUTH2_PROVIDER=authentik
      # - SECURITY_OAUTH2_AUTOCREATEUSER=false
      # - SECURITY_OAUTH2_BLOCKREGISTRATION=true

networks:
  proxy:
    external: true
